name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # 메인 브랜치에 push할 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodules # 서브모듈이 있는 경우
        run: git submodule update --init --recursive --remote

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # 사용하는 pnpm 버전

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: |
          pnpm build
          touch out/.nojekyll  # GitHub Pages가 _next 폴더를 무시하지 않도록 설정
        env:
          # 환경 변수가 필요한 경우 여기에 추가
          NEXT_PUBLIC_BASE_PATH: '' # GitHub Pages base path 설정
          NEXT_PUBLIC_GISCUS_REPO_NAME: ${{ secrets.GISCUS_REPO_NAME }}
          NEXT_PUBLIC_GISCUS_REPO_ID: ${{ secrets.GISCUS_REPO_ID }}
          NEXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.GISCUS_CATEGORY_ID }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 배포할 브랜치
          folder: out # Next.js 빌드 출력 폴더
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true # 배포 전 기존 파일 삭제
